import { pageMetadata } from "../lib/seo";
import Link from "next/link";
export const metadata = pageMetadata("/privacy", "プライバシーポリシー｜暮らしの計算機", "計算機の入力、お問い合わせ、A8.net・Google AdSenseの広告やCookieに伴う情報の取り扱いについて。");
export default function PrivacyPage() {
 return <main id="main-content" className="tool-page"><header className="tool-heading"><h1>プライバシーポリシー</h1><p>暮らしの計算機における情報の取り扱いを説明します。</p></header>
 <section className="explanation"><h2>1. 計算機への入力</h2><p>計算機に入力した金額は、お使いのブラウザ内で計算に使用します。当サイトの計算機には、入力額を運営者のサーバーへ送信する機能や、ブラウザへ永続保存する機能を設けていません。ページを閉じたり再読み込みしたりすると、入力が初期値に戻る場合があります。</p><p>サイトの閲覧に必要な通信や、以下の広告に関する通信は別に発生します。</p></section>
 <section className="explanation"><h2>2. お問い合わせ情報</h2><p>お問い合わせはXの「暮らしの計算機（@kura_culator）」で受け付けています。送信いただいたアカウント情報やお問い合わせ内容を、対応・連絡・不具合の確認に必要な範囲で利用します。公開投稿には個人情報や機密情報を記載しないでください。</p><p>X上での情報の取り扱いはXのプライバシーポリシーにも従います。当サイト内にお問い合わせフォームは設けていません。</p></section>
 <section className="explanation"><h2>3. 広告・外部送信</h2><p>A8.net（株式会社ファンコミュニケーションズ）のアフィリエイト広告を一部の記事に掲載しています。広告画像・計測画像の読み込み時や広告リンクのクリック時に、IPアドレス、ブラウザ等の端末情報、参照元ページ、Cookie等の識別情報が同社等へ送信される場合があります。送信先では広告表示、成果計測、不正防止等のために利用されます。</p><p>詳しい情報の種類や利用目的、Cookie等の取り扱いは、<a href="https://www.a8.net/privacy.html">A8.netのプライバシーに関する案内</a>および<a href="https://www.fancs.com/privacy/">ファンコミュニケーションズのプライバシーポリシー</a>をご確認ください。広告リンク先での情報の取り扱いは、各事業者のポリシーに従います。</p><h3>Google AdSenseについて</h3><p>当サイトにはGoogle AdSenseのコードを設置しています。広告の配信状況に応じ、Googleおよび第三者の広告配信事業者がCookie等を使用し、当サイトや他のサイトへの過去のアクセス情報に基づいて広告を表示する場合があります。IPアドレス、ブラウザや端末の情報、閲覧ページ、Cookie等の識別情報は、広告の配信・パーソナライズ・効果測定・不正防止などに利用される場合があります。</p><p>詳細は<a href="https://policies.google.com/technologies/partner-sites?hl=ja">Google：パートナーのサイトやアプリを使用する際の情報の取り扱い</a>をご確認ください。パーソナライズ広告の設定は<a href="https://myadcenter.google.com/">Googleのマイアドセンター</a>で管理できます。第三者事業者による広告の設定については<a href="https://www.aboutads.info/choices/">広告のオプトアウト案内（英語）</a>も参照できます。</p><p>同意メッセージが表示される場合は、メッセージ内で同意の選択や設定を行えます。</p><p>Cookieはブラウザ設定で制限・削除できます。設定により、広告の成果計測等が正常に行われない場合があります。</p></section>
 <section className="explanation"><h2>4. アクセス情報</h2><p>サイトの配信に伴い、ホスティング事業者がIPアドレスやリクエスト情報等を配信・保安のために取り扱う場合があります。Google Search Consoleを、検索結果での表示・クリック状況や登録状況の確認に利用しています。</p><p>現時点でGoogle Analyticsの計測タグは組み込んでいません。Google AdSenseに関する情報の取り扱いは、上記「広告・外部送信」をご確認ください。</p></section>
 <section className="explanation"><h2>5. 情報に関するお問い合わせ</h2><p>お問い合わせ情報の開示・訂正・削除等については、<Link href="/contact">お問い合わせ窓口</Link>へご連絡ください。ご本人からのご連絡であることを確認したうえで、法令に従って対応します。</p><p>本方針は運用の変更等に応じて更新し、このページでお知らせします。</p></section>
 <p className="field-hint mt-6">制定日：2026年9月5日／更新日：2026年9月18日</p></main>;
}
