import { pageMetadata } from "../lib/seo";
import ToolPage from "../components/ToolPage";
export const metadata = pageMetadata("/electricity-guide", "電気代の計算方法｜W・kWhの読み方と買替え比較", "消費電力Wと年間消費電力量kWhの使い分け、短時間の使用の換算、購入価格と年間電気代の差を比べる計算例を解説します。");
export default function Page() {
  return <ToolPage title="電気代を計算するとき、どの数字を使う？" description="家電の表示値を確認し、使用時間・電力量・料金単価を区別すると、比較の間違いを減らせます。">
    <section className="explanation"><h2>手元の数字から計算方法を選ぶ</h2><div className="table-scroll" tabIndex={0} role="region" aria-label="電気代の計算方法の選び方"><table className="comparison-table"><caption>製品の取扱説明書や省エネ表示で、単位・対象期間を確認してください。</caption><thead><tr><th scope="col">分かる数字</th><th scope="col">使う計算</th><th scope="col">注意すること</th></tr></thead><tbody><tr><th scope="row">消費電力W</th><td>W÷1,000×時間×単価</td><td>同じ電力で動く仮定。出力Wと混同しない。</td></tr><tr><th scope="row">年間消費電力量kWh/年</th><td>年間kWh×単価</td><td>使用時間をもう一度掛けない。表示の測定条件と実生活の差がある。</td></tr><tr><th scope="row">実測した電力量kWh</th><td>その期間のkWh×単価</td><td>測定期間と、家電単体か家全体かを確認する。</td></tr></tbody></table></div><p>買替えでは同じ用途・容量・使い方を前提に比較します。省エネ表示や製品選びの説明は、<a href="https://www.enecho.meti.go.jp/category/saving_and_new/saving/general/choice/index.html">資源エネルギー庁「機器の買換で省エネ節約」</a>を参照できます。</p></section>
    <section className="explanation"><h2>1日10分使う家電の計算例</h2><p>消費電力1,200W、1日10分、30日、単価31円/kWhと仮定します。10分は10÷60時間なので、1.2kW×（10÷60）時間×30日＝6kWh、料金は186円です。</p><p>10分を「10時間」として入れると60倍になってしまいます。計算機の時間欄には約0.1667時間と入力します。分から時間に変えるときは60で割ってください。</p><p>金額・電力・単価は説明用に設定したものです。製品や契約の実際の料金ではありません。</p></section>
    <section className="explanation"><h2>購入価格の差を電気代だけで比べる例</h2><p>同じ用途の製品Aが年400kWh、Bが年300kWh、単価31円という仮定なら、年額はAが12,400円、Bが9,300円で、Bが年3,100円低い計算です。</p><p>仮にBの購入価格が15,000円高ければ、15,000÷3,100で約4.84年使用したとき、単純な電気代差が購入価格差に届きます。ただし料金単価や使用環境の変化、故障・修理、処分費、買替え時期は反映していません。高価な製品が必ず得になるという判定ではありません。</p><p><a href="/electricity">年間kWhと料金単価を変更して比較する →</a></p></section>
    <section className="explanation"><h2>家電の計算額と、家全体の請求額が一致しない理由</h2><p>家電単体の計算は、その条件での電力量料金です。請求書には契約に応じて基本料金や調整額などが含まれるため、家電の試算をそのまま家全体の請求額にはできません。計算に使う単価に何が含まれているかを確認してください。</p><p>家全体の予算を作る際は、実際の請求書から月々の金額を生活費計算機へ入力します。季節で変わる場合は、ある1か月の料金だけを12倍せず、手元にある年間の明細を確認して予算を見直します。</p><p><a href="/living-cost">電気・ガス・水道を含む生活費を整理する →</a></p></section>
    <p className="field-hint mt-6">作成・編集：暮らしの計算機 ／ 更新日：2026年9月21日。計算例は当サイト作成。製品表示の参考：<a href="https://www.enecho.meti.go.jp/category/saving_and_new/saving/enterprise/retail/">資源エネルギー庁・小売事業者表示制度</a>。</p>
  </ToolPage>;
}
